-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 22:15:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lms` ;

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lms` DEFAULT CHARACTER SET utf8 ;
USE `lms` ;

-- -----------------------------------------------------
-- Table `lms`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Usuario` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`InfoEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`InfoEstudiante` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `semestre` INT NOT NULL,
  `Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`, `Usuario_idUsuario`),
  INDEX `fk_InfoEstudiante_Usuario1_idx` (`Usuario_idUsuario` ),
  CONSTRAINT `fk_InfoEstudiante_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `lms`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`pensum` (
  `idpensum` INT NOT NULL AUTO_INCREMENT,
  `pensumcol` VARCHAR(45) NULL,
  `InfoEstudiante_cedula` INT NOT NULL,
  `InfoEstudiante_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpensum`, `InfoEstudiante_cedula`, `InfoEstudiante_Usuario_idUsuario`),
  INDEX `fk_pensum_InfoEstudiante1_idx` (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario` ),
  CONSTRAINT `fk_pensum_InfoEstudiante1`
    FOREIGN KEY (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario`)
    REFERENCES `lms`.`InfoEstudiante` (`cedula` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`materia` (
  `idmateria` INT(4) unsigned ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cupo` INT NOT NULL,
  `creditos` INT NOT NULL,
  `veces_repite` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  `pensum_idpensum` INT NOT NULL,
  PRIMARY KEY (`idmateria`, `pensum_idpensum`),
  INDEX `fk_materia_pensum1_idx` (`pensum_idpensum` ),
  CONSTRAINT `fk_materia_pensum1`
    FOREIGN KEY (`pensum_idpensum`)
    REFERENCES `lms`.`pensum` (`idpensum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `InfoEstudiante_cedula` INT NOT NULL,
  `InfoEstudiante_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhorario`, `InfoEstudiante_cedula`, `InfoEstudiante_Usuario_idUsuario`),
  INDEX `fk_horario_InfoEstudiante1_idx` (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario` ),
  CONSTRAINT `fk_horario_InfoEstudiante1`
    FOREIGN KEY (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario`)
    REFERENCES `lms`.`InfoEstudiante` (`cedula` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`profesor` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`, `Usuario_idUsuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ),
  INDEX `fk_profesor_Usuario1_idx` (`Usuario_idUsuario` ),
  CONSTRAINT `fk_profesor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `lms`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`grupo` (
  `idgrupo` INT(4) unsigned ZEROFILL NOT NULL ,
  `materia_idmateria` INT(4) unsigned ZEROFILL NOT NULL ,
  `hora_inicio` INT NOT NULL,
  `hora_fin` INT NOT NULL,
  `horario_idhorario` INT NOT NULL,
  `profesor_cedula` INT NOT NULL,
  `profesor_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgrupo`, `materia_idmateria`, `horario_idhorario`, `profesor_cedula`, `profesor_Usuario_idUsuario`),
  INDEX `fk_grupo_materia_idx` (`materia_idmateria` ),
  INDEX `fk_grupo_horario1_idx` (`horario_idhorario` ),
  INDEX `fk_grupo_profesor1_idx` (`profesor_cedula` , `profesor_Usuario_idUsuario` ),
  CONSTRAINT `fk_grupo_materia`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `lms`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_horario1`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `lms`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_profesor1`
    FOREIGN KEY (`profesor_cedula` , `profesor_Usuario_idUsuario`)
    REFERENCES `lms`.`profesor` (`cedula` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`administrador` (
  `idadministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`, `Usuario_idUsuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ),
  INDEX `fk_administrador_Usuario1_idx` (`Usuario_idUsuario` ),
  CONSTRAINT `fk_administrador_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `lms`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`InfoEstudiante_has_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`InfoEstudiante_has_grupo` (
  `InfoEstudiante_cedula` INT NOT NULL,
  `InfoEstudiante_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  `grupo_idgrupo` INT(4) unsigned ZEROFILL NOT NULL ,
  `grupo_materia_idmateria` INT(4) unsigned ZEROFILL NOT NULL,
  `grupo_horario_idhorario` INT NOT NULL,
  `grupo_profesor_cedula` INT NOT NULL,
  `grupo_profesor_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`InfoEstudiante_cedula`, `InfoEstudiante_Usuario_idUsuario`, `grupo_idgrupo`, `grupo_materia_idmateria`, `grupo_horario_idhorario`, `grupo_profesor_cedula`, `grupo_profesor_Usuario_idUsuario`),
  INDEX `fk_InfoEstudiante_has_grupo_grupo1_idx` (`grupo_idgrupo` , `grupo_materia_idmateria` , `grupo_horario_idhorario` , `grupo_profesor_cedula` , `grupo_profesor_Usuario_idUsuario` ),
  INDEX `fk_InfoEstudiante_has_grupo_InfoEstudiante1_idx` (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario` ),
  CONSTRAINT `fk_InfoEstudiante_has_grupo_InfoEstudiante1`
    FOREIGN KEY (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario`)
    REFERENCES `lms`.`InfoEstudiante` (`cedula` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InfoEstudiante_has_grupo_grupo1`
    FOREIGN KEY (`grupo_idgrupo` , `grupo_materia_idmateria` , `grupo_horario_idhorario` , `grupo_profesor_cedula` , `grupo_profesor_Usuario_idUsuario`)
    REFERENCES `lms`.`grupo` (`idgrupo` , `materia_idmateria` , `horario_idhorario` , `profesor_cedula` , `profesor_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`materia_has_InfoEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`materia_has_InfoEstudiante` (
  `materia_idmateria` INT(4) unsigned ZEROFILL NOT NULL,
  `InfoEstudiante_cedula` INT NOT NULL,
  `InfoEstudiante_Usuario_idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`materia_idmateria`, `InfoEstudiante_cedula`, `InfoEstudiante_Usuario_idUsuario`),
  INDEX `fk_materia_has_InfoEstudiante_InfoEstudiante1_idx` (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario` ),
  INDEX `fk_materia_has_InfoEstudiante_materia1_idx` (`materia_idmateria` ),
  CONSTRAINT `fk_materia_has_InfoEstudiante_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `lms`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_InfoEstudiante_InfoEstudiante1`
    FOREIGN KEY (`InfoEstudiante_cedula` , `InfoEstudiante_Usuario_idUsuario`)
    REFERENCES `lms`.`InfoEstudiante` (`cedula` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
